apiVersion: ctrlmesh.kusionstack.io/v1alpha1
kind: CircuitBreaker
metadata:
  name: breaker-demo
  namespace: kusionstack-system
spec:
  rateLimitings:
  - bucket:
      burst: 1
      interval: 10s
      limit: 1
    name: deletePod
    recoverPolicy:
      sleepingWindowSize: 10m
      type: SleepingWindow
    resourceRules:
    - apiGroups:
      - ""
      namespaces:
      - '*'
      resources:
      - pods
      verbs:
      - delete
    triggerPolicy: LimiterOnly
  - bucket:
      burst: 200
      interval: 1s
      limit: 20
    name: trafficOffLimit
    restRules:
    - method: POST
      url: https://xxx.com/xxx/trafficOff
    triggerPolicy: LimiterOnly
  selector:
    matchLabels:
      control-plane: kusionstack-operating
  trafficInterceptRules:
  - contentType: Regexp
    contents:
    - .*(127.0.0.1).*
    interceptType: Whitelist
    methods:
    - POST
    - GET
    - PUT
    name: internalOnly